
//
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
//

using System.Reflection;


[assembly: AssemblyTitle("OneBoard Caption Translate")]
[assembly: AssemblyProduct("OneBoard Caption Translate")]
[assembly: AssemblyDescription("Lightweight real-time translation for Windows.")]
[assembly: AssemblyCompany("OneBoard")]
[assembly: AssemblyCopyright("Copyright 2024 SakiRinn and other contributors")]
[assembly: AssemblyMetadata("ModifiedBy", "OneBoard")]
[assembly: AssemblyMetadata("ProductWebsite", "https://oneboard.io.vn/oneboard-caption-translate/")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
